#!/usr/bin/env ruby
# frozen_string_literal: true

require './lib/vasevius_bot'

token = ENV['TELEGRAM_BOT_TOKEN']

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: "Hoy, #{message.from.first_name}, kuy dota lah!")
    when '/stop'
      bot.api.send_message(chat_id: message.chat.id, text: "Last of the last of the last lah, #{message.from.first_name}")
    end
  end
end